version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
      - echo Installing Playwright browsers...
      - npx playwright install --with-deps
      - echo Installing jq for Slack notification...
      - apt-get update && apt-get install -y jq

  build:
    commands:
      - echo Starting Playwright tests...
      - |
        npx playwright test --reporter=html > result.txt || true

      - echo Fetching Slack webhook from Secrets Manager...
      - |
        export SLACK_WEBHOOK=$(aws secretsmanager get-secret-value \
          --secret-id SlackPlaywrightWebhook \
          --query SecretString \
          --output text | jq -r '.SLACK_WEBHOOK_URL')

      - echo Checking for test failures...
      - |
        if grep -q "FAIL" result.txt; then
          echo "❌ Test failures detected. Preparing Slack alert..."

          export SUMMARY=$(tail -n 20 result.txt | sed 's/"/\\"/g')
          export SLACK_MESSAGE=$(jq -n --arg text ":robot_face: *Playwright Test Report - Failures Detected!*\n\`\`\`$SUMMARY\`\`\`" '{text: $text}')

          echo "Sending Slack notification..."
          curl -X POST -H 'Content-type: application/json' \
            --data "$SLACK_MESSAGE" "$SLACK_WEBHOOK"
        else
          echo "✅ All tests passed. No Slack alert sent."
        fi

artifacts:
  files:
    - "**/*"
  base-directory: playwright-report
  discard-paths: no
