version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
      - echo Installing Playwright browsers...
      - npx playwright install --with-deps

  build:
    commands:
      - echo Starting Playwright tests...
      - npx playwright test --reporter=html

artifacts:
  files:
    - '**/*'
  base-directory: playwright-report
  discard-paths: no
