name: Playwright Tests on PR to Main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests and Capture Logs
        run: |
          set -o pipefail
          npx playwright test 2>&1 | tee test-output.log

      - name: Send Slack Notification
        if: always()
        run: |
          STATUS="SUCCESS"
          COLOR="#36a64f"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="FAILURE"
            COLOR="#ff0000"
          fi

          LOG_CONTENT=$(tail -n 20 test-output.log | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')

          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"attachments\": [
                {
                  \"color\": \"$COLOR\",
                  \"title\": \"Playwright Tests - $STATUS\",
                  \"text\": \"$LOG_CONTENT\",
                  \"footer\": \"GitHub Actions | PR to main\"
                }
              ]
            }" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
